/** @file card0122.h
 * @brief file containing xpm for the card 0122
 * first digit is the color: red, green or blue
 * second digit is the symbol: diamond, oval or squiggle
 * third digit is the number: 1, 2 or 3
 * fourth digit is the shadding: open, stripped or solid
 */
/* XPM */
static char *card0122[] = {
/* columns rows colors */
"128 192 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                ================================================================================================                ",
"             ======================================================================================================             ",
"          ============================================================================================================          ",
"         ==============================================================================================================         ",
"       ==================================================================================================================       ",
"      ====================================================================================================================      ",
"     ======================================================================================================================     ",
"     ======================================================================================================================     ",
"    ========================================================================================================================    ",
"   ==========================================================================================================================   ",
"  ============================================================================================================================  ",
"  ============================================================================================================================  ",
"  ============================================================================================================================  ",
" ============================================================================================================================== ",
" ============================================================================================================================== ",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"=====================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=====================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"=======================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=======================",
"========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo========================",
"=========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo=========================",
"==========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==========================",
"===========================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===========================",
"============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo============================",
"==============================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo==============================",
"================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo================================",
"===================================oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo===================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
"================================================================================================================================",
" ============================================================================================================================== ",
" ============================================================================================================================== ",
"  ============================================================================================================================  ",
"  ============================================================================================================================  ",
"  ============================================================================================================================  ",
"   ==========================================================================================================================   ",
"    ========================================================================================================================    ",
"     ======================================================================================================================     ",
"     ======================================================================================================================     ",
"      ====================================================================================================================      ",
"       ==================================================================================================================       ",
"         ==============================================================================================================         ",
"          ============================================================================================================          ",
"             ======================================================================================================             ",
"                ================================================================================================                "
};
