/** @file exit_button.h
 * @brief file containing xpm for the exit button
 */
static char *exit_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                              xxxx                                                              ",
"                                                           xxxxxxxxxx                                                           ",
"                                                         xxxxxxxxxxxxxx                                                         ",
"                                                      xxxxxxxxxxxxxxxxxxxx                                                      ",
"                                                    xxxxxxxxxxxxxxxxxxxxxxxx                                                    ",
"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 ",
"                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               ",
"                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
"                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
"                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
"                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                      ",
"                                   xxxxxx=========xxx===xxx===xxx=========xxx=========xxxxxxx                                   ",
"                                 xxxxxxxx=========xxx===xxx===xxx=========xxx=========xxxxxxxxx                                 ",
"                              xxxxxxxxxxx=========xxx===xxx===xxx=========xxx=========xxxxxxxxxxx                               ",
"                             xxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxx                            ",
"                          xxxxxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxx                          ",
"                        xxxxxxxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxx                        ",
"                     xxxxxxxxxxxxxxxxxxxx======xxxxxxxxx===xxxxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxxxxx                     ",
"                    xxxxxxxxxxxxxxxxxxxxx======xxxxxxxxx===xxxxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
"                    xxxxxxxxxxxxxxxxxxxxx======xxxxxxxxx===xxxxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
"                     xxxxxxxxxxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxxxxx                     ",
"                       xxxxxxxxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxxx                        ",
"                          xxxxxxxxxxxxxxx===xxxxxxxxxx===x===xxxxxxx===xxxxxxxxx===xxxxxxxxxxxxxxxxxxxx                         ",
"                            xxxxxxxxxxxxx=========xxx===xxx===xxx=========xxxxxx===xxxxxxxxxxxxxxxxx                            ",
"                               xxxxxxxxxx=========xxx===xxx===xxx=========xxxxxx===xxxxxxxxxxxxxxx                              ",
"                                 xxxxxxxx=========xxx===xxx===xxx=========xxxxxx===xxxxxxxxxxxx                                 ",
"                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                    ",
"                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
"                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
"                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
"                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
"                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               ",
"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                  ",
"                                                    xxxxxxxxxxxxxxxxxxxxxxxx                                                    ",
"                                                      xxxxxxxxxxxxxxxxxxxx                                                      ",
"                                                         xxxxxxxxxxxxxx                                                         ",
"                                                           xxxxxxxxxx                                                           ",
"                                                             xxxxx                                                              ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
