/** @file hint_button.h
 * @brief file containing xpm for the hint button
 */
/* XPM */
static char *hint_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                              xxxx                                                              ",
"                                                           xxxxxxxxxx                                                           ",
"                                                         xxxxxxxxxxxxxx                                                         ",
"                                                      xxxxxxxxxxxxxxxxxxxx                                                      ",
"                                                    xxxxxxxxxxxxxxxxxxxxxxxx                                                    ",
"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 ",
"                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               ",
"                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
"                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
"                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
"                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                      ",
"                                   xxxxxx===xxx===xxx=========xxx===xxx===xxx=========xxxxxxx                                   ",
"                                 xxxxxxxx===xxx===xxx=========xxx===xxx===xxx=========xxxxxxxxx                                 ",
"                              xxxxxxxxxxx===xxx===xxx=========xxx===xxx===xxx=========xxxxxxxxxxx                               ",
"                             xxxxxxxxxxxx===xxx===xxxxxx===xxxxxx====xx===xxxxxx===xxxxxxxxxxxxxxxxx                            ",
"                          xxxxxxxxxxxxxxx===xxx===xxxxxx===xxxxxx====xx===xxxxxx===xxxxxxxxxxxxxxxxxxx                          ",
"                        xxxxxxxxxxxxxxxxx===xxx===xxxxxx===xxxxxx=====x===xxxxxx===xxxxxxxxxxxxxxxxxxxxx                        ",
"                     xxxxxxxxxxxxxxxxxxxx=========xxxxxx===xxxxxx=========xxxxxx===xxxxxxxxxxxxxxxxxxxxxxxx                     ",
"                    xxxxxxxxxxxxxxxxxxxxx=========xxxxxx===xxxxxx=========xxxxxx===xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
"                    xxxxxxxxxxxxxxxxxxxxx=========xxxxxx===xxxxxx=========xxxxxx===xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
"                     xxxxxxxxxxxxxxxxxxxx===xxx===xxxxxx===xxxxxx===x=====xxxxxx===xxxxxxxxxxxxxxxxxxxxxxxx                     ",
"                       xxxxxxxxxxxxxxxxxx===xxx===xxxxxx===xxxxxx===xx====xxxxxx===xxxxxxxxxxxxxxxxxxxxx                        ",
"                          xxxxxxxxxxxxxxx===xxx===xxxxxx===xxxxxx===xx====xxxxxx===xxxxxxxxxxxxxxxxxxxx                         ",
"                            xxxxxxxxxxxxx===xxx===xxx=========xxx===xxx===xxxxxx===xxxxxxxxxxxxxxxxx                            ",
"                               xxxxxxxxxx===xxx===xxx=========xxx===xxx===xxxxxx===xxxxxxxxxxxxxxx                              ",
"                                 xxxxxxxx===xxx===xxx=========xxx===xxx===xxxxxx===xxxxxxxxxxxx                                 ",
"                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                    ",
"                                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                     ",
"                                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                        ",
"                                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
"                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                             ",
"                                               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                               ",
"                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                  ",
"                                                    xxxxxxxxxxxxxxxxxxxxxxxx                                                    ",
"                                                      xxxxxxxxxxxxxxxxxxxx                                                      ",
"                                                         xxxxxxxxxxxxxx                                                         ",
"                                                           xxxxxxxxxx                                                           ",
"                                                             xxxxx                                                              ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
