/** @file nosets_button.h
 * @brief file containing xpm for the no sets button
 */
/* XPM */
static char *nosets_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                   ",
"                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                ",
"                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                              ",
"                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                            ",
"                           oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                           ",
"                          oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                          ",
"                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                         ",
"                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                        ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                      ooooo===ooo===ooo=========oooooooo=========ooo=========ooo=========ooo=========ooooo                      ",
"                     oooooo===ooo===ooo=========oooooooo=========ooo=========ooo=========ooo=========oooooo                     ",
"                     oooooo===ooo===ooo=========oooooooo=========ooo=========ooo=========ooo=========oooooo                     ",
"                     oooooo====oo===ooo===ooo===oooooooo===ooooooooo===oooooooooooo===oooooo===oooooooooooo                     ",
"                    ooooooo====oo===ooo===ooo===oooooooo===ooooooooo===oooooooooooo===oooooo===ooooooooooooo                    ",
"                    ooooooo=====o===ooo===ooo===oooooooo===ooooooooo===oooooooooooo===oooooo===ooooooooooooo                    ",
"                    ooooooo=========ooo===ooo===oooooooo=========ooo======ooooooooo===oooooo=========ooooooo                    ",
"                    ooooooo=========ooo===ooo===oooooooo=========ooo======ooooooooo===oooooo=========ooooooo                    ",
"                    ooooooo=========ooo===ooo===oooooooo=========ooo======ooooooooo===oooooo=========ooooooo                    ",
"                    ooooooo===o=====ooo===ooo===oooooooooooooo===ooo===oooooooooooo===oooooooooooo===ooooooo                    ",
"                    ooooooo===oo====ooo===ooo===oooooooooooooo===ooo===oooooooooooo===oooooooooooo===ooooooo                    ",
"                    ooooooo===oo====ooo===ooo===oooooooooooooo===ooo===oooooooooooo===oooooooooooo===ooooooo                    ",
"                     oooooo===ooo===ooo=========oooooooo=========ooo=========oooooo===oooooo=========oooooo                     ",
"                     oooooo===ooo===ooo=========oooooooo=========ooo=========oooooo===oooooo=========oooooo                     ",
"                     oooooo===ooo===ooo=========oooooooo=========ooo=========oooooo===oooooo=========oooooo                     ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                        ",
"                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                         ",
"                          oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                          ",
"                           oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                           ",
"                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                            ",
"                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                              ",
"                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                ",
"                                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                   ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
