/** @file pause_button.h
 * @brief file containing xpm for the pause button
 */
/* XPM */
static char *pause_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                iiiiiiii                        ",
"                                          iiiiiiii                                            iiiiiiiiiii                       ",
"                                     iiiiiiiiiiiiiiiiii                                      iiiiiiiiiiiii                      ",
"                                  iiiiiiiiiiiiiiiiiiiiiiiii                                iiiiiiiiiiiiiiii                     ",
"                               iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            iiiiiiiiiiiiiiiiiii                    ",
"                              iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                      iiiiiiiiiiiiiiiiiiiii                    ",
"                             iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                 iiiiiiiiiiiiiiiiiiiiiiii                    ",
"                            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                           iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                          iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiii=========iii=========iii===iii===iii=========iii=========iiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiii=========iii=========iii===iii===iii=========iii=========iiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiii=========iii=========iii===iii===iii=========iii=========iiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiii===iii===iii===iii===iii===iii===iii===iiiiiiiii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiii===iii===iii===iii===iii===iii===iii===iiiiiiiii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiii===iii===iii===iii===iii===iii===iii===iiiiiiiii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiii=========iii=========iii===iii===iii=========iii======iiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiii=========iii=========iii===iii===iii=========iii======iiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiii=========iii=========iii===iii===iii=========iii======iiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiii===iiiiiiiii===iii===iii===iii===iiiiiiiii===iii===iiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiii===iiiiiiiii===iii===iii===iii===iiiiiiiii===iii===iiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiii===iiiiiiiii===iii===iii===iii===iiiiiiiii===iii===iiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiii===iiiiiiiii===iii===iii=========iii=========iii=========iiiiiiiiiiii                       ",
"                      iiiiiiiiiiiiii===iiiiiiiii===iii===iii=========iii=========iii=========iiiiiiiiiii                        ",
"                      iiiiiiiiiiiiii===iiiiiiiii===iii===iii=========iii=========iii=========iiiiiiiiii                         ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                         ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                          ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                             ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiii        iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                               ",
"                        iiiiiiiiiiiiiiiiiiiiiii               iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                                ",
"                        iiiiiiiiiiiiiiiiiiiii                     iiiiiiiiiiiiiiiiiiiiiiiiiii                                   ",
"                        iiiiiiiiiiiiiiiiiiii                         iiiiiiiiiiiiiiiiiiiii                                      ",
"                         iiiiiiiiiiiiiiii                                  iiiiiiiiiiii                                         ",
"                         iiiiiiiiiiiiiii                                                                                        ",
"                          iiiiiiiiiiii                                                                                          ",
"                            iiiiiiii                                                                                            ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
