/** @file play_button.h
 * @brief file containing xpm for the play button
 */
/* XPM */
static char *play_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                iiiiiiii                        ",
"                                          iiiiiiii                                            iiiiiiiiiii                       ",
"                                     iiiiiiiiiiiiiiiiii                                      iiiiiiiiiiiii                      ",
"                                  iiiiiiiiiiiiiiiiiiiiiiiii                                iiiiiiiiiiiiiiii                     ",
"                               iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            iiiiiiiiiiiiiiiiiii                    ",
"                              iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                      iiiiiiiiiiiiiiiiiiiii                    ",
"                             iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                 iiiiiiiiiiiiiiiiiiiiiiii                    ",
"                            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                           iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                          iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiii===iii===iii===iiiiiiiii===iii===iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiii===iii===iii===iiiiiiiii===iii===iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiii===iii===iii===iiiiiiiii===iii===iii===iii===iiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iiii===i===iiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iiii===i===iiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiii=========iii===iiiiiiiii=========iiii===i===iiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiii===iii===iiiiii===iiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiii===iii===iiiiii===iiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiii===iii===iiiiii===iiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiii===iiiiiiiii=========iii===iii===iiiiii===iiiiiiiiiiiiiiiiiiiii                       ",
"                      iiiiiiiiiiiiiiiiiiii===iiiiiiiii=========iii===iii===iiiiii===iiiiiiiiiiiiiiiiiiii                        ",
"                      iiiiiiiiiiiiiiiiiiii===iiiiiiiii=========iii===iii===iiiiii===iiiiiiiiiiiiiiiiiii                         ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                         ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                          ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                             ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiii        iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                               ",
"                        iiiiiiiiiiiiiiiiiiiiiii               iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                                ",
"                        iiiiiiiiiiiiiiiiiiiii                     iiiiiiiiiiiiiiiiiiiiiiiiiii                                   ",
"                        iiiiiiiiiiiiiiiiiiii                         iiiiiiiiiiiiiiiiiiiii                                      ",
"                         iiiiiiiiiiiiiiii                                  iiiiiiiiiiii                                         ",
"                         iiiiiiiiiiiiiii                                                                                        ",
"                          iiiiiiiiiiii                                                                                          ",
"                            iiiiiiii                                                                                            ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
