/** @file save_button.h
 * @brief file containing xpm for the save button
 */
/* XPM */
static char *save_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                   ",
"                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                ",
"                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                              ",
"                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                            ",
"                           oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                           ",
"                          oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                          ",
"                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                         ",
"                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                        ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                      oooooooooooooooooooo=========ooo=========ooo===ooo===ooo=========ooooooooooooooooooo                      ",
"                     ooooooooooooooooooooo=========ooo=========ooo===ooo===ooo=========oooooooooooooooooooo                     ",
"                     ooooooooooooooooooooo=========ooo=========ooo===ooo===ooo=========oooooooooooooooooooo                     ",
"                     ooooooooooooooooooooo===ooooooooo===ooo===ooo===ooo===ooo===oooooooooooooooooooooooooo                     ",
"                    oooooooooooooooooooooo===ooooooooo===ooo===ooo===ooo===ooo===ooooooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooo===ooooooooo===ooo===ooo===ooo===ooo===ooooooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooo=========ooo=========ooo===ooo===ooo======oooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooo=========ooo=========ooo===ooo===ooo======oooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooo=========ooo=========ooo===ooo===ooo======oooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooooooooo===ooo===ooo===oooo===o===oooo===ooooooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooooooooo===ooo===ooo===oooo===o===oooo===ooooooooooooooooooooooooooo                    ",
"                    oooooooooooooooooooooooooooo===ooo===ooo===oooo===o===oooo===ooooooooooooooooooooooooooo                    ",
"                     ooooooooooooooooooooo=========ooo===ooo===oooooo===oooooo=========oooooooooooooooooooo                     ",
"                     ooooooooooooooooooooo=========ooo===ooo===oooooo===oooooo=========oooooooooooooooooooo                     ",
"                     ooooooooooooooooooooo=========ooo===ooo===oooooo===oooooo=========oooooooooooooooooooo                     ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                      oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                      ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                       oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                       ",
"                        oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                        ",
"                         oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                         ",
"                          oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                          ",
"                           oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                           ",
"                            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                            ",
"                              oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                              ",
"                                oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                ",
"                                   oooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                   ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
