/** @file set_button.h
 * @brief file containing xpm for the set button
 */
/* XPM */
static char *set_button[] = {
/* columns rows colors */
"128 78 5",
"  64",
"= 63",
"o 44",
"x 57",
"i 10",
/* pixels */
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                iiiiiiii                        ",
"                                          iiiiiiii                                            iiiiiiiiiii                       ",
"                                     iiiiiiiiiiiiiiiiii                                      iiiiiiiiiiiii                      ",
"                                  iiiiiiiiiiiiiiiiiiiiiiiii                                iiiiiiiiiiiiiiii                     ",
"                               iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            iiiiiiiiiiiiiiiiiii                    ",
"                              iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                      iiiiiiiiiiiiiiiiiiiii                    ",
"                             iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                 iiiiiiiiiiiiiiiiiiiiiiii                    ",
"                            iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                           iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                          iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                         iiiiiiiiiiiiiiiiiiiiiii=========iii=========iii=========iiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiiiiiiiii=========iii=========iii=========iiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiiiiiiiii=========iii=========iii=========iiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                        iiiiiiiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiiiiiiiii===iiiiiiiii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiiii                    ",
"                       iiiiiiiiiiiiiiiiiiiiiiiii=========iii======iiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiiiiiiiii=========iii======iiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiiiiiiiii=========iii======iiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiiii                     ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii===iii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii===iii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii===iii===iiiiiiiiiiii===iiiiiiiiiiiiiiiiiiiiiiiiiii                      ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiii=========iii=========iiiiii===iiiiiiiiiiiiiiiiiiiiiiiiii                       ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiii=========iii=========iiiiii===iiiiiiiiiiiiiiiiiiiiiiiii                        ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiii=========iii=========iiiiii===iiiiiiiiiiiiiiiiiiiiiiiii                         ",
"                      iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                         ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                          ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                            ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                             ",
"                       iiiiiiiiiiiiiiiiiiiiiiiiiiiii        iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                               ",
"                        iiiiiiiiiiiiiiiiiiiiiii               iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii                                ",
"                        iiiiiiiiiiiiiiiiiiiii                     iiiiiiiiiiiiiiiiiiiiiiiiiii                                   ",
"                        iiiiiiiiiiiiiiiiiiii                         iiiiiiiiiiiiiiiiiiiii                                      ",
"                         iiiiiiiiiiiiiiii                                  iiiiiiiiiiii                                         ",
"                         iiiiiiiiiiiiiii                                                                                        ",
"                          iiiiiiiiiiii                                                                                          ",
"                            iiiiiiii                                                                                            ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
};
